server:
  port: 8088

file:
  path: "C://Users//user//Desktop//上银国泰//sso//统一认证集成指南//samlsp1//WebContent//saml-sp.properties"

webcheck:
  url: "http://222.93.106.197:39095/mgmt-b/account/loginssobysy"

wsdl:
  url: "http://10.240.41.10:31201/iamgate/services/IamgateWebService?wsdl"
