server:
  port: 9088

file:
  path: "/root/saml/saml-sp.properties"

webcheck:
  url: "http://127.0.0.1:59095/mgmt-b/account/loginssobysy"
  errUrl: "http://10.240.177.13:59095/#/error"

wsdl:
  url: "http://10.240.41.10:31201/iamgate/services/IamgateWebService?wsdl"
